// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 23 09:37:31 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:41:39 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:44:44 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:57:56 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 09:00:15 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 09:13:09 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 09:27:58 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 09:29:08 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 09:31:57 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 10:05:16 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 13:15:12 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 13:15:25 CEST 2009"
