// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 22:21:42 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 22:22:06 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 22:22:26 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 22:25:18 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 22:25:44 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 22:52:20 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 23:28:43 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Mon Jun 29 23:28:57 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:55:57 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:56:21 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:56:30 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:56:35 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:56:53 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:57:18 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 00:57:24 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:00:36 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:09:02 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:09:15 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:29:52 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:41:00 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:44:41 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 01:47:35 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:23:51 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:28:07 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:31:28 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:31:39 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:31:51 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:33:16 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:33:29 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:34:56 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:35:22 CEST 2009"
// this file is generated by make-and-flash.sh
#define BUILD "Tue Jun 30 08:56:59 CEST 2009"
